version: '3.7'

services:
  db:
    container_name: db
    image: mariadb
    restart: always
    ports:
      - '3309:3306'
    env_file:
      - ./../apps/api/env/.env.local
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ../data/db-data:/var/lib/mysql
      - ../data/mariadb.cnf:/etc/mysql/mariadb.cnf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
