name: Deploy new version to Docker Hub

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: docker.io
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run tests
        run: |
          npm ci
          npm run test:all

      - name: Build app
        run: |
          npm ci
          npm run build:all:production

      - name: Extract version from package.json
        run: |
          echo "TAG=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          push: true
          images: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}
          tags: |
            latest
            ${{ env.TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
